#!/usr/bin/env python3
"""Regression test for the DualDeck Host/Client menu lifecycle bug (real
user report, 2026-08-27): "Check for updates / changing settings / saving
settings all close DualDeck Host instead of returning to the menu."

`host/dualdeck-host.sh` and `client/dualdeck-client.sh` don't exist as
files in this repo -- they're generated by heredocs inside
`scripts/build-release.sh` (search for
`cat > "${pkg_dir}/host/dualdeck-host.sh" <<'WRAP'` and the client
equivalent). Running the full `build-release.sh` to get them would mean
compiling melonDS/Azahar/Cemu from scratch (20-90+ minutes) just to test
a bash menu loop, so this test extracts the two heredocs directly out of
`scripts/build-release.sh` with a small parser, writes them out as real
scripts, and drives them like a real (non-graphical -- no kdialog on
PATH, so both scripts use their terminal-fallback numbered prompts)
terminal session would: scripted stdin choices, real subprocess, real
exit code.

What's being verified is exactly the bug report: the process must still
be running (and show the menu again) after an action completes
successfully, after one fails, and after backing out of a submenu -- and
must terminate only via the menu's own explicit Exit/Cancel choice.

Usage:
    python3 tests/host_client_menu_lifecycle_test.py
"""

import re
import shutil
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BUILD_RELEASE = REPO_ROOT / "scripts" / "build-release.sh"

STUB = "#!/usr/bin/env bash\necho \"stub: $(basename \"$0\") called with: $*\" >&2\nexit 0\n"
FAILING_STUB = "#!/usr/bin/env bash\necho \"stub: $(basename \"$0\") simulated failure\" >&2\nexit 1\n"


def extract_heredoc(src: str, marker: str) -> str:
    idx = src.index(marker)
    start = src.index("\n", idx) + 1
    end = src.index("\nWRAP\n", start)
    return src[start:end]


def write_exec(path: Path, content: str) -> None:
    path.write_text(content)
    path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def build_host_harness(root: Path, src: str, failing: set[str] = frozenset()) -> Path:
    host_dir = root / "host"
    internal_dir = host_dir / "internal"
    internal_dir.mkdir(parents=True)

    write_exec(host_dir / "dualdeck-host.sh",
               extract_heredoc(src, "cat > \"${pkg_dir}/host/dualdeck-host.sh\" <<'WRAP'"))
    write_exec(root / "check-for-updates.sh",
               "#!/usr/bin/env bash\necho \"DualDeck 0.1.0 -- you're on the latest version.\"\n")

    for name in ("apply-update.sh", "install-steam-shortcut.sh", "uninstall-steam-shortcut.sh",
                 "uninstall-host-control-daemon.sh", "reconfigure-cemu-controls.sh",
                 "launch-host.sh", "run-host-azahar.sh", "run-host-cemu.sh",
                 "launch-custom-emulator.sh", "launch-emudeck-integration.sh",
                 "install-host-control-daemon.sh", "install-branch.sh"):
        write_exec(internal_dir / name, FAILING_STUB if name in failing else STUB)

    # dualdeck_branch.sh is a real repo file (not a heredoc) -- copy it so
    # sourcing it at the top of dualdeck-host.sh succeeds. Point its
    # network calls nowhere: this test only exercises the lifecycle loop,
    # not branch discovery (see dualdeck_branch_selector_test.py for
    # that), so an unreachable API host just makes every call fail fast
    # and cleanly rather than actually reaching GitHub.
    shutil.copy(REPO_ROOT / "scripts" / "lib" / "dualdeck_branch.sh", internal_dir / "dualdeck_branch.sh")

    return host_dir


def build_client_harness(root: Path, src: str, failing: set[str] = frozenset()) -> Path:
    client_dir = root / "client"
    internal_dir = client_dir / "internal"
    internal_dir.mkdir(parents=True)

    write_exec(client_dir / "dualdeck-client.sh",
               extract_heredoc(src, "cat > \"${pkg_dir}/client/dualdeck-client.sh\" <<'WRAP'"))
    write_exec(root / "check-for-updates.sh",
               "#!/usr/bin/env bash\necho \"DualDeck 0.1.0 -- you're on the latest version.\"\n")

    for name in ("apply-update.sh", "install-steam-shortcut.sh", "uninstall-steam-shortcut.sh",
                 "configure-trackpad-experiment.sh", "run-client.sh", "install-branch.sh"):
        write_exec(internal_dir / name, FAILING_STUB if name in failing else STUB)
    # configure-trackpad-experiment.sh --status is queried for a menu
    # label on every choose_action() call -- give it a real, harmless
    # implementation instead of the generic stub above (which would exit
    # 0 with no stdout, which is also fine, but this is closer to real
    # behavior and exercises the --status branch explicitly).
    write_exec(internal_dir / "configure-trackpad-experiment.sh",
               "#!/usr/bin/env bash\n"
               "if [[ \"$1\" == \"--status\" ]]; then echo enabled; exit 0; fi\n"
               "echo \"stub: configure-trackpad-experiment.sh called with: $*\" >&2\nexit 0\n")

    shutil.copy(REPO_ROOT / "scripts" / "lib" / "dualdeck_branch.sh", internal_dir / "dualdeck_branch.sh")
    # steam_input_config.py is invoked directly via `python3 ...` from
    # steam-remove -- a real, harmless no-op stands in for it.
    write_exec(internal_dir / "steam_input_config.py",
               "#!/usr/bin/env python3\nimport sys\nsys.exit(0)\n")

    return client_dir


def run_menu(script_dir: Path, script_name: str, stdin_choices: list[str], env_extra: dict | None = None):
    env = {"PATH": "/usr/bin:/bin", "HOME": str(script_dir.parent / "home")}
    Path(env["HOME"]).mkdir(parents=True, exist_ok=True)
    if env_extra:
        env.update(env_extra)
    proc = subprocess.run(
        [f"./{script_name}"],
        cwd=script_dir,
        input="\n".join(stdin_choices) + "\n",
        capture_output=True,
        text=True,
        env=env,
        timeout=20,
    )
    return proc


def count_menu_appearances(proc: subprocess.CompletedProcess, title: str) -> int:
    # The menu prompt itself is deliberately written to stderr (see the
    # generated script's own comment: choose_action()'s stdout is
    # captured as the actual selection, so menu text can't leak onto it)
    # -- info()/echo results from a completed action go to stdout. Check
    # both combined so this doesn't care which stream a given line landed
    # on.
    combined = proc.stdout + proc.stderr
    return len(re.findall(rf"^{re.escape(title)}$", combined, re.MULTILINE))


def run() -> int:
    src = BUILD_RELEASE.read_text()
    failures = []

    def check(condition: bool, message: str):
        if condition:
            print(f"[ok] {message}")
        else:
            print(f"[FAIL] {message}")
            failures.append(message)

    # --- Host: a successful action (Check for updates) returns to the menu ---
    with tempfile.TemporaryDirectory() as tmp:
        host_dir = build_host_harness(Path(tmp), src)
        # 6=Check for updates, 9=Advanced (just to touch it), 4=Back, 10=Exit
        proc = run_menu(host_dir, "dualdeck-host.sh", ["6", "10"])
        check(proc.returncode == 0, "host: clean exit code after Check for updates then Exit")
        check(count_menu_appearances(proc, "DualDeck Host") == 2,
              "host: main menu redisplayed after Check for updates (not exited)")

    # --- Host: a failing action still returns to the menu, not a crash ---
    with tempfile.TemporaryDirectory() as tmp:
        host_dir = build_host_harness(Path(tmp), src, failing={"install-steam-shortcut.sh"})
        proc = run_menu(host_dir, "dualdeck-host.sh", ["3", "10"])
        check(proc.returncode == 0, "host: clean exit code after a failed action then Exit")
        check(count_menu_appearances(proc, "DualDeck Host") == 2,
              "host: main menu redisplayed after a failed Add-to-Steam (not exited/crashed)")

    # --- Host: backing out of the Launch submenu returns to the main menu ---
    with tempfile.TemporaryDirectory() as tmp:
        host_dir = build_host_harness(Path(tmp), src)
        # 1=Launch..., 6=Back (choose_emulator's terminal fallback), 10=Exit
        proc = run_menu(host_dir, "dualdeck-host.sh", ["1", "6", "10"])
        check(proc.returncode == 0, "host: clean exit after cancelling the Launch submenu then Exit")
        check(count_menu_appearances(proc, "DualDeck Host") == 2,
              "host: main menu redisplayed after backing out of 'Which system?' (not exited)")
        check("Which system?" in proc.stderr, "host: the Launch submenu was actually shown")

    # --- Host: backing out of the Host Control daemon submenu returns to the main menu ---
    with tempfile.TemporaryDirectory() as tmp:
        host_dir = build_host_harness(Path(tmp), src)
        # 2=Host Control daemon submenu, 3=Back, 10=Exit
        proc = run_menu(host_dir, "dualdeck-host.sh", ["2", "3", "10"])
        check(proc.returncode == 0, "host: clean exit after cancelling the daemon submenu then Exit")
        check(count_menu_appearances(proc, "DualDeck Host") == 2,
              "host: main menu redisplayed after backing out of the daemon submenu (not exited)")

    # --- Host: RetroDECK setup tool missing reports clearly, returns to the main menu ---
    with tempfile.TemporaryDirectory() as tmp:
        host_dir = build_host_harness(Path(tmp), src)
        # 8=RetroDECK: Cemu compatibility setup (tool not present in this
        # harness at all -- emudeck-integration/scripts/ is never
        # created), 10=Exit
        proc = run_menu(host_dir, "dualdeck-host.sh", ["8", "10"])
        check(proc.returncode == 0, "host: clean exit after the RetroDECK tool-missing message then Exit")
        check(count_menu_appearances(proc, "DualDeck Host") == 2,
              "host: main menu redisplayed after the RetroDECK setup tool is reported missing")
        check("retrodeck-setup.sh" in (proc.stdout + proc.stderr),
              "host: the missing-tool message names retrodeck-setup.sh")

    # --- Host: RetroDECK setup submenu (Status), then backing out, returns to the main menu ---
    with tempfile.TemporaryDirectory() as tmp:
        host_dir = build_host_harness(Path(tmp), src)
        retrodeck_tool_dir = host_dir / "emudeck-integration" / "scripts"
        retrodeck_tool_dir.mkdir(parents=True)
        write_exec(retrodeck_tool_dir / "retrodeck-setup.sh",
                   "#!/usr/bin/env bash\n"
                   "echo \"stub: retrodeck-setup.sh called with: $*\"\n")
        # 8=RetroDECK submenu, 2=Status (no confirm() needed), 4=Back,
        # 10=Exit
        proc = run_menu(host_dir, "dualdeck-host.sh", ["8", "2", "4", "10"])
        check(proc.returncode == 0, "host: clean exit after using the RetroDECK Status action then Exit")
        check(count_menu_appearances(proc, "DualDeck Host") == 2,
              "host: main menu redisplayed after backing out of the RetroDECK submenu")
        check("retrodeck-setup.sh called with: --status" in proc.stdout,
              "host: the RetroDECK submenu's Status choice calls retrodeck-setup.sh --status")

    # --- Host: only the explicit Exit choice terminates it ---
    with tempfile.TemporaryDirectory() as tmp:
        host_dir = build_host_harness(Path(tmp), src)
        # 6, 3, 5 (three real actions in a row), then Exit
        proc = run_menu(host_dir, "dualdeck-host.sh", ["6", "3", "5", "10"])
        check(proc.returncode == 0, "host: clean exit after a run of several actions then Exit")
        check(count_menu_appearances(proc, "DualDeck Host") == 4,
              "host: menu redisplayed after every one of several consecutive actions")

    # --- Client: identical shape of bug/fix ---
    with tempfile.TemporaryDirectory() as tmp:
        client_dir = build_client_harness(Path(tmp), src)
        # 5=Check for updates, 7=Exit
        proc = run_menu(client_dir, "dualdeck-client.sh", ["5", "7"])
        check(proc.returncode == 0, "client: clean exit code after Check for updates then Exit")
        check(count_menu_appearances(proc, "DualDeck") >= 2,
              "client: main menu redisplayed after Check for updates (not exited)")

    with tempfile.TemporaryDirectory() as tmp:
        client_dir = build_client_harness(Path(tmp), src, failing={"install-steam-shortcut.sh"})
        # 2=Add to Steam (fails), 7=Exit
        proc = run_menu(client_dir, "dualdeck-client.sh", ["2", "7"])
        check(proc.returncode == 0, "client: clean exit code after a failed action then Exit")
        check(count_menu_appearances(proc, "DualDeck") >= 2,
              "client: main menu redisplayed after a failed Add-to-Steam (not exited/crashed)")

    # --- Client: toggling the trackpad-experiment setting (a save) returns to the menu ---
    with tempfile.TemporaryDirectory() as tmp:
        client_dir = build_client_harness(Path(tmp), src)
        # 4=trackpad-experiment, y=confirm, 7=Exit
        proc = run_menu(client_dir, "dualdeck-client.sh", ["4", "y", "7"])
        check(proc.returncode == 0, "client: clean exit code after saving a setting then Exit")
        check(count_menu_appearances(proc, "DualDeck") >= 2,
              "client: main menu redisplayed after saving the trackpad-experiment setting")

    # --- Client: cancelling the trackpad-experiment confirm dialog also returns to the menu ---
    with tempfile.TemporaryDirectory() as tmp:
        client_dir = build_client_harness(Path(tmp), src)
        # 4=trackpad-experiment, n=decline confirm, 7=Exit
        proc = run_menu(client_dir, "dualdeck-client.sh", ["4", "n", "7"])
        check(proc.returncode == 0, "client: clean exit code after declining a confirm dialog then Exit")
        check(count_menu_appearances(proc, "DualDeck") >= 2,
              "client: main menu redisplayed after declining the trackpad-experiment confirm")

    if failures:
        print(f"\n{len(failures)} check(s) failed:")
        for f in failures:
            print(f"  - {f}")
        return 1

    print("\nHOST/CLIENT MENU LIFECYCLE TEST PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(run())
