# Turns each NAME=path in FONTS into a byte array in OUT_DIR's
# embedded_fonts.{h,cpp}. Run at build time by CMakeLists.txt.
file(MAKE_DIRECTORY "${OUT_DIR}")
string(REPLACE "%%" ";" FONTS "${FONTS}")
set(header "#pragma once\n\n#include <cstddef>\n\nnamespace dualdeck::hostui {\n\nstruct EmbeddedFont {\n    const unsigned char* data;\n    std::size_t size;\n};\n\n")
set(source "#include \"embedded_fonts.h\"\n\nnamespace dualdeck::hostui {\n\n")
foreach(entry IN LISTS FONTS)
    string(REGEX MATCH "^[^=]+" name "${entry}")
    string(REGEX REPLACE "^[^=]+=" "" path "${entry}")
    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR size "${hex_length} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n" bytes "${bytes}")
    string(APPEND header "extern const EmbeddedFont ${name};\n")
    string(APPEND source "static const unsigned char ${name}Data[] = {\n${bytes}\n};\nconst EmbeddedFont ${name}{${name}Data, ${size}};\n\n")
endforeach()
string(APPEND header "\n} // namespace dualdeck::hostui\n")
string(APPEND source "} // namespace dualdeck::hostui\n")
file(WRITE "${OUT_DIR}/embedded_fonts.h" "${header}")
file(WRITE "${OUT_DIR}/embedded_fonts.cpp" "${source}")
